#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libcdr
Version  : 0.1.5
Release  : 6
URL      : https://dev-www.libreoffice.org/src/libcdr-0.1.5.tar.xz
Source0  : https://dev-www.libreoffice.org/src/libcdr-0.1.5.tar.xz
Summary  : Library for importing and converting Corel Draw Documents
Group    : Development/Tools
License  : MPL-2.0 MPL-2.0-no-copyleft-exception
Requires: libcdr-bin = %{version}-%{release}
Requires: libcdr-lib = %{version}-%{release}
Requires: libcdr-license = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : doxygen
BuildRequires : pkgconfig(cppunit)
BuildRequires : pkgconfig(icu-i18n)
BuildRequires : pkgconfig(lcms2)
BuildRequires : pkgconfig(librevenge-0.0)
BuildRequires : pkgconfig(librevenge-generators-0.0)
BuildRequires : pkgconfig(librevenge-stream-0.0)
BuildRequires : pkgconfig(zlib)

%description
libcdr is a library for reading and converting CDR images

%package bin
Summary: bin components for the libcdr package.
Group: Binaries
Requires: libcdr-license = %{version}-%{release}

%description bin
bin components for the libcdr package.


%package dev
Summary: dev components for the libcdr package.
Group: Development
Requires: libcdr-lib = %{version}-%{release}
Requires: libcdr-bin = %{version}-%{release}
Provides: libcdr-devel = %{version}-%{release}
Requires: libcdr = %{version}-%{release}

%description dev
dev components for the libcdr package.


%package doc
Summary: doc components for the libcdr package.
Group: Documentation

%description doc
doc components for the libcdr package.


%package lib
Summary: lib components for the libcdr package.
Group: Libraries
Requires: libcdr-license = %{version}-%{release}

%description lib
lib components for the libcdr package.


%package license
Summary: license components for the libcdr package.
Group: Default

%description license
license components for the libcdr package.


%prep
%setup -q -n libcdr-0.1.5
cd %{_builddir}/libcdr-0.1.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1592623255
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1592623255
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libcdr
cp %{_builddir}/libcdr-0.1.5/COPYING.MPL %{buildroot}/usr/share/package-licenses/libcdr/9744cedce099f727b327cd9913a1fdc58a7f5599
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cdr2raw
/usr/bin/cdr2text
/usr/bin/cdr2xhtml
/usr/bin/cmx2raw
/usr/bin/cmx2text
/usr/bin/cmx2xhtml

%files dev
%defattr(-,root,root,-)
/usr/include/libcdr-0.1/libcdr/CDRDocument.h
/usr/include/libcdr-0.1/libcdr/CMXDocument.h
/usr/include/libcdr-0.1/libcdr/libcdr.h
/usr/include/libcdr-0.1/libcdr/libcdr_api.h
/usr/lib64/libcdr-0.1.so
/usr/lib64/pkgconfig/libcdr-0.1.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libcdr/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcdr-0.1.so.1
/usr/lib64/libcdr-0.1.so.1.0.5

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libcdr/9744cedce099f727b327cd9913a1fdc58a7f5599
