#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
Name     : libcdr
Version  : 0.1.7
Release  : 10
URL      : https://dev-www.libreoffice.org/src/libcdr-0.1.7.tar.xz
Source0  : https://dev-www.libreoffice.org/src/libcdr-0.1.7.tar.xz
Summary  : Library for importing and converting Corel Draw Documents
Group    : Development/Tools
License  : MPL-2.0 MPL-2.0-no-copyleft-exception
Requires: libcdr-bin = %{version}-%{release}
Requires: libcdr-lib = %{version}-%{release}
Requires: libcdr-license = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : buildreq-configure
BuildRequires : doxygen
BuildRequires : pkgconfig(cppunit)
BuildRequires : pkgconfig(icu-i18n)
BuildRequires : pkgconfig(lcms2)
BuildRequires : pkgconfig(librevenge-0.0)
BuildRequires : pkgconfig(librevenge-generators-0.0)
BuildRequires : pkgconfig(librevenge-stream-0.0)
BuildRequires : pkgconfig(zlib)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
libcdr is a library for reading and converting CDR images

%package bin
Summary: bin components for the libcdr package.
Group: Binaries
Requires: libcdr-license = %{version}-%{release}

%description bin
bin components for the libcdr package.


%package dev
Summary: dev components for the libcdr package.
Group: Development
Requires: libcdr-lib = %{version}-%{release}
Requires: libcdr-bin = %{version}-%{release}
Provides: libcdr-devel = %{version}-%{release}
Requires: libcdr = %{version}-%{release}

%description dev
dev components for the libcdr package.


%package doc
Summary: doc components for the libcdr package.
Group: Documentation

%description doc
doc components for the libcdr package.


%package lib
Summary: lib components for the libcdr package.
Group: Libraries
Requires: libcdr-license = %{version}-%{release}

%description lib
lib components for the libcdr package.


%package license
Summary: license components for the libcdr package.
Group: Default

%description license
license components for the libcdr package.


%prep
%setup -q -n libcdr-0.1.7
cd %{_builddir}/libcdr-0.1.7
pushd ..
cp -a libcdr-0.1.7 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1683816701
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1683816701
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libcdr
cp %{_builddir}/libcdr-%{version}/COPYING.MPL %{buildroot}/usr/share/package-licenses/libcdr/9744cedce099f727b327cd9913a1fdc58a7f5599 || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/cdr2raw
/V3/usr/bin/cdr2text
/V3/usr/bin/cdr2xhtml
/V3/usr/bin/cmx2raw
/V3/usr/bin/cmx2text
/V3/usr/bin/cmx2xhtml
/usr/bin/cdr2raw
/usr/bin/cdr2text
/usr/bin/cdr2xhtml
/usr/bin/cmx2raw
/usr/bin/cmx2text
/usr/bin/cmx2xhtml

%files dev
%defattr(-,root,root,-)
/V3/usr/lib64/libcdr-0.1.so
/usr/include/libcdr-0.1/libcdr/CDRDocument.h
/usr/include/libcdr-0.1/libcdr/CMXDocument.h
/usr/include/libcdr-0.1/libcdr/libcdr.h
/usr/include/libcdr-0.1/libcdr/libcdr_api.h
/usr/lib64/libcdr-0.1.so
/usr/lib64/pkgconfig/libcdr-0.1.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/libcdr/*

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libcdr-0.1.so.1
/V3/usr/lib64/libcdr-0.1.so.1.0.7
/usr/lib64/libcdr-0.1.so.1
/usr/lib64/libcdr-0.1.so.1.0.7

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libcdr/9744cedce099f727b327cd9913a1fdc58a7f5599
